# set default task and default training config based on task
defaults:
  - task: TiagoDualMultiObjFetching
  - train: TiagoDualMultiObjFetchingBHyRL
  - slurm: Slurm_chain
  - hydra/job_logging: disabled

# Task name - used to pick the class to load
task_name: TiagoDualMultiObjFetching
# experiment name. defaults to name of training config
experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: 1
# enable/disable headless mode and rendering (in pygame window)
headless: True
render: True #TODO check render for getting annotator to deliver data
get_renders: False

# seed - set to -1 to choose random seed
seed: -1
# set to True for deterministic performance
torch_deterministic: False
# (Optional) Use the isaac sim configuration from file
sim_app_cfg_path: "" # "/isaac_app_configs/omni.isaac.sim.python.kit"
# set the maximum number of learning iterations to train for. overrides default per-environment setting
# max_iterations: 500

## Device config
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'cpu' # 'gpu'
# whether to use cpu or gpu physx
sim_device: 'cpu' # 'gpu'
# used for gpu simulation only - device id for running sim and task if pipeline=gpu
device_id: 0
# device to run RL
rl_device: 'cuda:0' #'cpu' # 'cuda:0'

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs

# RL Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False
# used to set checkpoint path
checkpoint: ''
# number of seeds to run (run sequentially by default)
num_seeds: 1

results_dir: ''

# Wandb settings (optional)
# TODO
wandb_activate: True
# wandb_group: ''
# wandb_name: ${train.params.config.name}
# wandb_entity: ''
# wandb_project: 'omniisaacgymenvs'

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .